version: '3.3'

  
services:

  web:
    depends_on:
      - redis
    build: .
    # stdin_open: true
    # tty: true
    hostname: redis

    ports:
      - "8080:8080"
    networks:
      - frontend
    # volumes:
    #   - type: bind
    #     source: "./target"
    #     target: "/"
    #     read_only: true
    # entrypoint: ["java", "-jar", "URLShortener-0.0.1-SNAPSHOT.jar"]

    links:
      - redis

  redis:
    # image: redis
    
    # stdin_open: true
    # tty: true
    # networks:
    #         - spring-cloud-network 
      
    build: ./Redis
    # # hostname: redisDB
    # hostname: "0.0.0.0"
      
    ports:
      - "6379:6379"
    networks:
      - backend


networks:
  backend:
  frontend:        
    

        

