version: '3.3'

  
services:

  web:
    depends_on:
      - redis
    build: .
    # stdin_open: true
    # tty: true
    environment: 
      SPRING_REDIS.HOST: redis

    ports:
      - "8080:8080"
    networks:
      - backend
    # volumes:
    #   - type: bind
    #     source: "./target"
    #     target: "/"
    #     read_only: true
    # entrypoint: ["java", "-jar", "URLShortener-0.0.1-SNAPSHOT.jar"]

    links:
      - redis:localhost

  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname:
      redis
    ports:
      - "6379:6379"
    networks:
      - backend


    # image: redis
    
    # stdin_open: true
    # tty: true
    # networks:
    #         - spring-cloud-network 
      
    # build: ./Redis
    # # # hostname: redisDB
    # hostname: redis
      
    # ports:
    #   - "6379:6379"
    # networks:
    #   - backend


networks:
  backend:
          
    

        

