version: '3.3'

  
services:
  # Spring boot app service
  web:
    depends_on:
      - redis
    # This builds from dockerfile within current Directory
    build: .

    environment: 
      SPRING_REDIS_HOST: redis

    ports:
      - "8080:8080"
    networks:
      - backend
    # volumes:
    #   - type: bind
    #     source: "./target"
    #     target: "/"
    #     read_only: true
    # entrypoint: ["java", "-jar", "URLShortener-0.0.1-SNAPSHOT.jar"]

    links:
      - redis:localhost

  # Redis Service
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname:
      redis
    ports:
      - "6379:6379"
    networks:
      - backend


networks:
  backend:
          
    

        

